"""
Read in raw CPS data file and structure to be used in future scripts
Input file: asec2016_pubuse_v3.dat
Run time is approximately two hours
"""
from collections import OrderedDict
import pandas as pd
from tqdm import tqdm


def h_recs(rec):
    """
    Process a household record from the raw CPS file.

    Parameters
    ----------
    rec: String containing a CPS household record

    Returns
    -------
    DataFrame with the final record

    """
    record = OrderedDict()

    record['hrecord'] = [int(rec[0])]
    record['h_seq'] = [int(rec[1:6])]
    record['hhpos'] = [int(rec[6:8])]
    record['hunits'] = [int(rec[8])]
    record['hefaminc'] = [int(rec[9:11])]
    record['h_respnm'] = [int(rec[11:13])]
    record['h_year'] = [int(rec[13:17])]
    record['h_hhtype'] = [int(rec[19])]
    record['h_numper'] = [int(rec[20:22])]
    record['hnumfam'] = [int(rec[22:24])]
    record['h_type'] = [int(rec[24])]
    record['h_month'] = [int(rec[25:27])]
    record['h_mis'] = [int(rec[28])]
    record['h_hhnum'] = [int(rec[29])]
    record['h_livqrt'] = [int(rec[30:32])]
    record['h_typebc'] = [int(rec[32:34])]
    record['h_tenure'] = [int(rec[34])]
    record['h_telhhd'] = [int(rec[35])]
    record['h_telavl'] = [int(rec[36])]
    record['h_telint'] = [int(rec[37])]
    record['gereg'] = [int(rec[38])]
    record['gestfips'] = [int(rec[41:43])]
    record['gtcbsa'] = [int(rec[43:48])]
    record['gtco'] = [int(rec[48:51])]
    record['gtcbsast'] = [int(rec[51])]
    record['gtmetsta'] = [int(rec[52])]
    record['gtindvpc'] = [int(rec[53])]
    record['gtcbsasz'] = [int(rec[54])]
    record['gtcsa'] = [int(rec[55:58])]
    record['hunder15'] = [int(rec[59:61])]
    record['hh5to18'] = [int(rec[67:69])]
    record['hhotlun'] = [int(rec[69])]
    record['hhotno'] = [int(rec[70])]
    record['hflunch'] = [int(rec[71])]
    record['hflunno'] = [int(rec[72])]
    record['hpublic'] = [int(rec[73])]
    record['hlorent'] = [int(rec[74])]
    record['hfoodsp'] = [int(rec[75])]
    record['hfoodno'] = [int(rec[76])]
    record['hfoodmo'] = [int(rec[78:80])]
    record['hengast'] = [int(rec[84])]
    record['hengval'] = [int(rec[85:89])]
    record['hinc_ws'] = [int(rec[89])]
    record['hwsval'] = [int(rec[90:97])]
    record['hinc_se'] = [int(rec[97])]
    record['hseval'] = [int(rec[98:105])]
    record['hinc_fr'] = [int(rec[105])]
    record['hfrval'] = [int(rec[106:113])]
    record['hinc_uc'] = [int(rec[113])]
    record['hucval'] = [int(rec[114:121])]
    record['hinc_wc'] = [int(rec[121])]
    record['hwcval'] = [int(rec[122:129])]
    record['hss_yn'] = [int(rec[129])]
    record['hssval'] = [int(rec[130:137])]
    record['hssi_yn'] = [int(rec[137])]
    record['hssival'] = [int(rec[138:144])]
    record['hpaw_yn'] = [int(rec[144])]
    record['hpawval'] = [int(rec[145:151])]
    record['hvet_yn'] = [int(rec[151])]
    record['hvetval'] = [int(rec[152:159])]
    record['hsur_yn'] = [int(rec[159])]
    record['hsurval'] = [int(rec[160:167])]
    record['hdis_yn'] = [int(rec[167])]
    record['hdisval'] = [int(rec[168:175])]
    record['hret_yn'] = [int(rec[175])]
    record['hretval'] = [int(rec[176:183])]
    record['hint_yn'] = [int(rec[183])]
    record['hintval'] = [int(rec[184:191])]
    record['hdiv_yn'] = [int(rec[191])]
    record['hdivval'] = [int(rec[192:199])]
    record['hrnt_yn'] = [int(rec[199])]
    record['hrntval'] = [int(rec[200:207])]
    record['hed_yn'] = [int(rec[207])]
    record['hedval'] = [int(rec[208:215])]
    record['hcsp_yn'] = [int(rec[215])]
    record['hcspval'] = [int(rec[216:223])]
    record['hfin_yn'] = [int(rec[231])]
    record['hfinval'] = [int(rec[232:239])]
    record['hoi_yn'] = [int(rec[239])]
    record['hoival'] = [int(rec[240:247])]
    record['htotval'] = [int(rec[247:255])]
    record['hearnval'] = [int(rec[255:263])]
    record['hothval'] = [int(rec[263:271])]
    record['hhinc'] = [int(rec[271:273])]
    record['hmcare'] = [int(rec[273])]
    record['hmcaid'] = [int(rec[274])]
    record['hchamp'] = [int(rec[275])]
    record['hhi_yn'] = [int(rec[276])]
    record['hhstatus'] = [int(rec[277])]
    record['hunder18'] = [int(rec[278:280])]
    record['htop5pct'] = [int(rec[280])]
    record['hpctcut'] = [int(rec[281:283])]
    record['hsup_wgt'] = [float(rec[286:292] + '.' + rec[292:294])]
    record['h1tenure'] = [int(rec[294])]
    record['h1livqrt'] = [int(rec[296])]
    record['h1telhhd'] = [int(rec[298])]
    record['h1telavl'] = [int(rec[299])]
    record['h1telint'] = [int(rec[300])]
    record['i_hhotlu'] = [int(rec[307])]
    record['i_hhotno'] = [int(rec[308])]
    record['i_hflunc'] = [int(rec[309])]
    record['i_hflunn'] = [int(rec[310])]
    record['i_hpubli'] = [int(rec[311])]
    record['i_hloren'] = [int(rec[312])]
    record['i_hfoods'] = [int(rec[313])]
    record['i_hfdval'] = [int(rec[314])]
    record['i_hfoodn'] = [int(rec[315])]
    record['i_hfoodm'] = [int(rec[316])]
    record['i_hengas'] = [int(rec[317])]
    record['i_hengva'] = [int(rec[318])]
    record['h_idnum2'] = [str(rec[319:324])]
    record['prop_tax'] = [int(rec[331:336])]
    record['housret'] = [int(rec[336:341])]
    record['hrhtype'] = [int(rec[341:343])]
    record['h_idnum1'] = [str(rec[343:358])]
    record['i_hunits'] = [int(rec[358])]
    record['hrpaidcc'] = [int(rec[366])]
    record['hprop_val'] = [int(rec[367:375])]
    record['thprop_val'] = [int(rec[375])]
    record['i_propval'] = [int(rec[376])]
    record['hrnumwic'] = [int(rec[382:384])]
    record['hrwicyn'] = [int(rec[385])]
    record['hfdval'] = [int(rec[386:391])]
    record['tcare_val'] = [int(rec[391])]
    record['care_val'] = [int(rec[392:398])]
    record['i_careval'] = [int(rec[398])]
    record['hpres_mort'] = [int(rec[399])]

    return pd.DataFrame(record)


def f_recs(rec):
    """
    Process a family record from the raw CPS file.

    Parameters
    ----------
    rec: String containing a CPS family record

    Returns
    -------
    DataFrame with the final record

    """
    record = OrderedDict()

    record['frecord'] = [int(rec[0])]
    record['fh_seq'] = [int(rec[1:6])]
    record['ffpos'] = [int(rec[6:8])]
    record['fkind'] = [int(rec[8])]
    record['ftype'] = [int(rec[9])]
    record['fpersons'] = [int(rec[10:12])]
    record['fheadidx'] = [int(rec[12:14])]
    record['fwifeidx'] = [int(rec[14:16])]
    record['fhusbidx'] = [int(rec[16:18])]
    record['fspouidx'] = [int(rec[18:20])]
    record['flastidx'] = [int(rec[20:22])]
    record['fmlasidx'] = [int(rec[22:24])]
    record['fownu6'] = [int(rec[24])]
    record['fownu18'] = [int(rec[26])]
    record['frelu6'] = [int(rec[27])]
    record['frelu18'] = [int(rec[28])]
    record['fpctcut'] = [int(rec[29:31])]
    record['fpovcut'] = [int(rec[31:36])]
    record['famlis'] = [int(rec[36])]
    record['povll'] = [int(rec[37:39])]
    record['frspov'] = [int(rec[39:41])]
    record['frsppct'] = [int(rec[41:46])]
    record['finc_ws'] = [int(rec[46])]
    record['fwsval'] = [int(rec[47:54])]
    record['finc_se'] = [int(rec[54])]
    record['fseval'] = [int(rec[55:62])]
    record['finc_fr'] = [int(rec[62])]
    record['ffrval'] = [int(rec[63:70])]
    record['finc_uc'] = [int(rec[70])]
    record['fucval'] = [int(rec[71:78])]
    record['finc_wc'] = [int(rec[78])]
    record['fwcval'] = [int(rec[79:86])]
    record['finc_ss'] = [int(rec[86])]
    record['fssval'] = [int(rec[87:94])]
    record['finc_ssi'] = [int(rec[94])]
    record['fssival'] = [int(rec[95:101])]
    record['finc_paw'] = [int(rec[101])]
    record['fpawval'] = [int(rec[102:108])]
    record['finc_vet'] = [int(rec[108])]
    record['fvetval'] = [int(rec[109:116])]
    record['finc_sur'] = [int(rec[116])]
    record['fsurval'] = [int(rec[117:124])]
    record['finc_dis'] = [int(rec[124])]
    record['fdisval'] = [int(rec[125:132])]
    record['finc_ret'] = [int(rec[132])]
    record['fretval'] = [int(rec[133:140])]
    record['finc_int'] = [int(rec[140])]
    record['fintval'] = [int(rec[141:148])]
    record['finc_div'] = [int(rec[148])]
    record['fdivval'] = [int(rec[149:156])]
    record['finc_rnt'] = [int(rec[156])]
    record['frntval'] = [int(rec[157:164])]
    record['finc_ed'] = [int(rec[164])]
    record['fedval'] = [int(rec[165:172])]
    record['finc_csp'] = [int(rec[172])]
    record['fcspval'] = [int(rec[173:180])]
    record['finc_fin'] = [int(rec[188])]
    record['ffinval'] = [int(rec[189:196])]
    record['finc_oi'] = [int(rec[196])]
    record['foival'] = [int(rec[197:204])]
    record['ftotval'] = [int(rec[204:212])]
    record['fearnval'] = [int(rec[212:220])]
    record['fothval'] = [int(rec[220:228])]
    record['ftot_r'] = [int(rec[228:230])]
    record['fspanish'] = [int(rec[230])]
    record['fsup_wgt'] = [float(rec[232:238] + '.' + rec[238:240])]
    record['ffposold'] = [int(rec[240:242])]
    record['f_mv_fs'] = [int(rec[242:247])]
    record['f_mv_sl'] = [int(rec[247:251])]
    record['fhoussub'] = [int(rec[260:263])]
    record['fhip_val'] = [int(rec[271:278])]
    record['fmoop'] = [int(rec[278:285])]
    record['fotc_val'] = [int(rec[285:291])]
    record['fmed_val'] = [int(rec[291:298])]
    record['i_fhipval'] = [int(rec[298])]

    return pd.DataFrame(record)


def p_recs(rec):
    """
    Process a person record from the raw CPS file.

    Parameters
    ----------
    rec: String containing a CPS person record

    Returns
    -------
    DataFrame with the final record

    """
    record = OrderedDict()

    record['precord'] = [int(rec[0])]
    record['ph_seq'] = [int(rec[1:6])]
    record['pppos'] = [int(rec[6:8])]
    record['ppposold'] = [int(rec[8:10])]
    record['a_lineno'] = [int(rec[10:12])]
    record['a_parent'] = [int(rec[12:14])]
    record['a_exprrp'] = [int(rec[14:16])]
    record['perrp'] = [int(rec[16:18])]
    record['a_age'] = [int(rec[18:20])]
    record['a_maritl'] = [int(rec[20])]
    record['a_spouse'] = [int(rec[21:23])]
    record['a_sex'] = [int(rec[23])]
    record['a_hga'] = [int(rec[24:26])]
    record['prdtrace'] = [int(rec[26:28])]
    record['p_stat'] = [int(rec[28])]
    record['prpertyp'] = [int(rec[29])]
    record['pehspnon'] = [int(rec[30])]
    record['prdthsp'] = [int(rec[31])]
    record['a_famnum'] = [int(rec[32:34])]
    record['a_famtyp'] = [int(rec[34])]
    record['a_famrel'] = [int(rec[35])]
    record['a_pfrel'] = [int(rec[36])]
    record['hhdrel'] = [int(rec[37])]
    record['famrel'] = [int(rec[38:40])]
    record['hhdfmx'] = [int(rec[40:42])]
    record['parent'] = [int(rec[42])]
    record['age1'] = [int(rec[43:45])]
    record['phf_seq'] = [int(rec[45:47])]
    record['pf_seq'] = [int(rec[47:49])]
    record['pecohab'] = [int(rec[49:51])]
    record['pelnmom'] = [int(rec[51:53])]
    record['pelndad'] = [int(rec[53:55])]
    record['pemomtyp'] = [int(rec[55:57])]
    record['pedadtyp'] = [int(rec[57:59])]
    record['peafever'] = [int(rec[59:61])]
    record['peafwhn1'] = [int(rec[61:63])]
    record['peafwhn2'] = [int(rec[63:65])]
    record['peafwhn3'] = [int(rec[65:67])]
    record['peafwhn4'] = [int(rec[67:69])]
    record['pedisear'] = [int(rec[69:71])]
    record['pediseye'] = [int(rec[71:73])]
    record['pedisrem'] = [int(rec[73:75])]
    record['pedisphy'] = [int(rec[75:77])]
    record['pedisdrs'] = [int(rec[77:79])]
    record['pedisout'] = [int(rec[79:81])]
    record['prdisflg'] = [int(rec[81:83])]
    record['penatvty'] = [int(rec[83:86])]
    record['pemntvty'] = [int(rec[86:89])]
    record['pefntvty'] = [int(rec[89:92])]
    record['peinusyr'] = [int(rec[92:94])]
    record['prcitshp'] = [int(rec[94])]
    record['peridnum'] = [str(rec[95:117])]
    record['fl_665'] = [int(rec[117])]
    record['prdasian'] = [int(rec[118:120])]
    record['a_fnlwgt'] = [float(rec[138:144] + '.' + rec[144:146])]
    record['a_ernlwt'] = [float(rec[146:152] + '.' + rec[152:154])]
    record['marsupwt'] = [float(rec[154:160] + '.' + rec[160:162])]
    record['a_hrs1'] = [int(rec[162:164])]
    record['a_uslft'] = [int(rec[164])]
    record['a_whyabs'] = [int(rec[165])]
    record['a_payabs'] = [int(rec[166])]
    record['peioind'] = [int(rec[167:171])]
    record['peioocc'] = [int(rec[171:175])]
    record['a_clswkr'] = [int(rec[175])]
    record['a_wkslk'] = [int(rec[176:179])]
    record['a_whenlj'] = [int(rec[179])]
    record['a_nlflj'] = [int(rec[180])]
    record['a_wantjb'] = [int(rec[181])]
    record['prerelg'] = [int(rec[182])]
    record['a_uslhrs'] = [int(rec[183:185])]
    record['a_hrlywk'] = [int(rec[185])]
    record['a_hrspay'] = [float(rec[186:188] + '.' + rec[188:190])]
    record['a_grswk'] = [int(rec[190:194])]
    record['a_unmem'] = [int(rec[194])]
    record['a_uncov'] = [int(rec[195])]
    record['a_enrlw'] = [int(rec[196])]
    record['a_hscol'] = [int(rec[197])]
    record['a_ftpt'] = [int(rec[198])]
    record['a_lfsr'] = [int(rec[199])]
    record['a_untype'] = [int(rec[200])]
    record['a_wkstat'] = [int(rec[201])]
    record['a_explf'] = [int(rec[202])]
    record['a_wksch'] = [int(rec[203])]
    record['a_civlf'] = [int(rec[204])]
    record['a_ftlf'] = [int(rec[205])]
    record['a_mjind'] = [int(rec[206:208])]
    record['a_dtind'] = [int(rec[208:210])]
    record['a_mjocc'] = [int(rec[210:212])]
    record['a_dtocc'] = [int(rec[212:214])]
    record['peio1cow'] = [int(rec[214:216])]
    record['prcow1'] = [int(rec[216])]
    record['pemlr'] = [int(rec[217])]
    record['pruntype'] = [int(rec[218])]
    record['prwkstat'] = [int(rec[219:221])]
    record['prptrea'] = [int(rec[221:223])]
    record['prdisc'] = [int(rec[223])]
    record['peabsrsn'] = [int(rec[224:226])]
    record['prnlfsch'] = [int(rec[226])]
    record['pehruslt'] = [int(rec[227:230])]
    record['workyn'] = [int(rec[250])]
    record['wrk_ck'] = [int(rec[251])]
    record['wtemp'] = [int(rec[252])]
    record['nwlook'] = [int(rec[253])]
    record['nwlkwk'] = [int(rec[254:256])]
    record['rsnnotw'] = [int(rec[256])]
    record['wkswork'] = [int(rec[257:259])]
    record['wkcheck'] = [int(rec[259])]
    record['losewks'] = [int(rec[260])]
    record['lknone'] = [int(rec[261])]
    record['lkweeks'] = [int(rec[262:264])]
    record['lkstrch'] = [int(rec[264])]
    record['pyrsn'] = [int(rec[265])]
    record['phmemprs'] = [int(rec[266])]
    record['hrswk'] = [int(rec[267:269])]
    record['hrcheck'] = [int(rec[269])]
    record['ptyn'] = [int(rec[270])]
    record['ptweeks'] = [int(rec[271:273])]
    record['ptrsn'] = [int(rec[273])]
    record['wexp'] = [int(rec[274:276])]
    record['wewkrs'] = [int(rec[276])]
    record['welknw'] = [int(rec[277])]
    record['weuemp'] = [int(rec[278])]
    record['earner'] = [int(rec[279])]
    record['clwk'] = [int(rec[280])]
    record['weclw'] = [int(rec[281])]
    record['poccu2'] = [int(rec[282:284])]
    record['wemocg'] = [int(rec[284:286])]
    record['weind'] = [int(rec[286:288])]
    record['wemind'] = [int(rec[288:290])]
    record['ljcw'] = [int(rec[290])]
    record['industry'] = [int(rec[291:295])]
    record['occup'] = [int(rec[295:299])]
    record['noemp'] = [int(rec[299])]
    record['nxtres'] = [int(rec[320:322])]
    record['mig_cbst'] = [int(rec[322])]
    record['migsame'] = [int(rec[323])]
    record['mig_reg'] = [int(rec[324])]
    record['mig_st'] = [int(rec[325:327])]
    record['mig_dscp'] = [int(rec[327])]
    record['gediv'] = [int(rec[328])]
    record['mig_div'] = [int(rec[329:331])]
    record['mig_mtr1'] = [int(rec[331:333])]
    record['mig_mtr3'] = [int(rec[333])]
    record['mig_mtr4'] = [int(rec[334])]
    record['ern_yn'] = [int(rec[351])]
    record['ern_srce'] = [int(rec[352])]
    record['ern_otr'] = [int(rec[353])]
    record['ern_val'] = [int(rec[354:361])]
    record['wageotr'] = [int(rec[361])]
    record['wsal_yn'] = [int(rec[362])]
    record['wsal_val'] = [int(rec[363:370])]
    record['ws_val'] = [int(rec[370:377])]
    record['seotr'] = [int(rec[377])]
    record['semp_yn'] = [int(rec[378])]
    record['semp_val'] = [int(rec[379:386])]
    record['se_val'] = [int(rec[386:392])]
    record['frmotr'] = [int(rec[392])]
    record['frse_yn'] = [int(rec[393])]
    record['frse_val'] = [int(rec[394:401])]
    record['frm_val'] = [int(rec[401:407])]
    record['uc_yn'] = [int(rec[407])]
    record['subuc'] = [int(rec[408])]
    record['strkuc'] = [int(rec[409])]
    record['uc_val'] = [int(rec[410:415])]
    record['wc_yn'] = [int(rec[415])]
    record['wc_type'] = [int(rec[416])]
    record['wc_val'] = [int(rec[417:422])]
    record['ss_yn'] = [int(rec[422])]
    record['ss_val'] = [int(rec[423:428])]
    record['resnss1'] = [int(rec[428])]
    record['resnss2'] = [int(rec[429])]
    record['sskidyn'] = [int(rec[430])]
    record['ssi_yn'] = [int(rec[431])]
    record['ssi_val'] = [int(rec[432:437])]
    record['resnssi1'] = [int(rec[437])]
    record['resnssi2'] = [int(rec[438])]
    record['ssikidyn'] = [int(rec[439])]
    record['paw_yn'] = [int(rec[440])]
    record['paw_typ'] = [int(rec[441])]
    record['paw_mon'] = [int(rec[442:444])]
    record['paw_val'] = [int(rec[444:449])]
    record['vet_yn'] = [int(rec[449])]
    record['vet_typ1'] = [int(rec[450])]
    record['vet_typ2'] = [int(rec[451])]
    record['vet_typ3'] = [int(rec[452])]
    record['vet_typ4'] = [int(rec[453])]
    record['vet_typ5'] = [int(rec[454])]
    record['vet_qva'] = [int(rec[455])]
    record['vet_val'] = [int(rec[456:461])]
    record['sur_yn'] = [int(rec[461])]
    record['sur_sc1'] = [int(rec[462:464])]
    record['sur_sc2'] = [int(rec[464:466])]
    record['sur_val1'] = [int(rec[466:471])]
    record['sur_val2'] = [int(rec[471:476])]
    record['srvs_val'] = [int(rec[476:482])]
    record['dis_hp'] = [int(rec[482])]
    record['dis_cs'] = [int(rec[483])]
    record['dis_yn'] = [int(rec[484])]
    record['dis_sc1'] = [int(rec[485:487])]
    record['dis_sc2'] = [int(rec[487:489])]
    record['dis_val1'] = [int(rec[489:494])]
    record['dis_val2'] = [int(rec[494:499])]
    record['dsab_val'] = [int(rec[499:505])]
    record['ret_yn'] = [int(rec[505])]
    record['ret_sc1'] = [int(rec[506])]
    record['ret_sc2'] = [int(rec[507])]
    record['ret_val1'] = [int(rec[508:513])]
    record['ret_val2'] = [int(rec[513:518])]
    record['rtm_val'] = [int(rec[518:524])]
    record['int_yn'] = [int(rec[524])]
    record['int_val'] = [int(rec[525:530])]
    record['div_yn'] = [int(rec[530])]
    record['div_val'] = [int(rec[532:538])]
    record['rnt_yn'] = [int(rec[538])]
    record['rnt_val'] = [int(rec[539:544])]
    record['ed_yn'] = [int(rec[544])]
    record['oed_typ1'] = [int(rec[545])]
    record['oed_typ2'] = [int(rec[546])]
    record['oed_typ3'] = [int(rec[547])]
    record['ed_val'] = [int(rec[548:553])]
    record['csp_yn'] = [int(rec[553])]
    record['csp_val'] = [int(rec[554:559])]
    record['fin_yn'] = [int(rec[565])]
    record['fin_val'] = [int(rec[566:571])]
    record['oi_off'] = [int(rec[571:573])]
    record['oi_yn'] = [int(rec[573])]
    record['oi_val'] = [int(rec[574:579])]
    record['ptotval'] = [int(rec[579:587])]
    record['pearnval'] = [int(rec[587:595])]
    record['pothval'] = [int(rec[595:603])]
    record['ptot_r'] = [int(rec[603:605])]
    record['perlis'] = [int(rec[605])]
    record['pov_univ'] = [int(rec[606])]
    record['wicyn'] = [int(rec[607])]
    record['mcare'] = [int(rec[628])]
    record['mcaid'] = [int(rec[634])]
    record['champ'] = [int(rec[640])]
    record['hi_yn'] = [int(rec[641])]
    record['hiown'] = [int(rec[642])]
    record['hiemp'] = [int(rec[643])]
    record['hipaid'] = [int(rec[644])]
    record['emcontrb'] = [int(rec[645:649])]
    record['hi'] = [int(rec[649])]
    record['hityp'] = [int(rec[650])]
    record['dephi'] = [int(rec[651])]
    record['hilin1'] = [int(rec[652:654])]
    record['hilin2'] = [int(rec[654:656])]
    record['paid'] = [int(rec[656])]
    record['hiout'] = [int(rec[657])]
    record['priv'] = [int(rec[658])]
    record['prityp'] = [int(rec[659])]
    record['depriv'] = [int(rec[660])]
    record['pilin1'] = [int(rec[661:663])]
    record['pilin2'] = [int(rec[663:665])]
    record['pout'] = [int(rec[665])]
    record['out'] = [int(rec[666])]
    record['care'] = [int(rec[667])]
    record['caid'] = [int(rec[668])]
    record['mon'] = [int(rec[669:671])]
    record['oth'] = [int(rec[671])]
    record['otyp_1'] = [int(rec[672])]
    record['otyp_2'] = [int(rec[673])]
    record['otyp_3'] = [int(rec[674])]
    record['otyp_4'] = [int(rec[675])]
    record['otyp_5'] = [int(rec[676])]
    record['othstper'] = [int(rec[677])]
    record['othstyp1'] = [int(rec[678:680])]
    record['othstyp2'] = [int(rec[680:682])]
    record['othstyp3'] = [int(rec[682:684])]
    record['othstyp4'] = [int(rec[684:686])]
    record['othstyp5'] = [int(rec[686:688])]
    record['othstyp6'] = [int(rec[688:690])]
    record['hea'] = [int(rec[690])]
    record['ihsflg'] = [int(rec[691])]
    record['ahiper'] = [int(rec[692])]
    record['ahityp1'] = [int(rec[693:695])]
    record['ahityp2'] = [int(rec[695:697])]
    record['ahityp3'] = [int(rec[697:699])]
    record['ahityp4'] = [int(rec[699:701])]
    record['ahityp5'] = [int(rec[701:703])]
    record['ahityp6'] = [int(rec[703:705])]
    record['pchip'] = [int(rec[705])]
    record['cov_gh'] = [int(rec[706])]
    record['cov_hi'] = [int(rec[707])]
    record['ch_mc'] = [int(rec[708])]
    record['ch_hi'] = [int(rec[709])]
    record['marg_tax'] = [int(rec[723:725])]
    record['ctc_crd'] = [int(rec[725:730])]
    record['penplan'] = [int(rec[730])]
    record['penincl'] = [int(rec[731])]
    record['filestat'] = [int(rec[732])]
    record['dep_stat'] = [int(rec[733:735])]
    record['eit_cred'] = [int(rec[735:739])]
    record['actc_crd'] = [int(rec[739:743])]
    record['fica'] = [int(rec[743:748])]
    record['fed_ret'] = [int(rec[748:754])]
    record['agi'] = [int(rec[754:761])]
    record['tax_inc'] = [int(rec[762:769])]
    record['fedtax_bc'] = [int(rec[769:776])]
    record['fedtax_ac'] = [int(rec[776:783])]
    record['statetax_bc'] = [int(rec[783:789])]
    record['statetax_ac'] = [int(rec[789:795])]
    record['prswkxpns'] = [int(rec[795:799])]
    record['paidccyn'] = [int(rec[799])]
    record['paidcyna'] = [int(rec[800])]
    record['moop'] = [int(rec[801:808])]
    record['phip_val'] = [int(rec[808:814])]
    record['potc_val'] = [int(rec[814:819])]
    record['pmed_val'] = [int(rec[819:825])]
    record['chsp_val'] = [int(rec[825:830])]
    record['chsp_yn'] = [int(rec[830])]
    record['chelsew_yn'] = [int(rec[831])]
    record['axrrp'] = [int(rec[852])]
    record['axage'] = [int(rec[853])]
    record['axmaritl'] = [int(rec[854])]
    record['axspouse'] = [int(rec[855])]
    record['axsex'] = [int(rec[856])]
    record['axhga'] = [int(rec[857])]
    record['pxrace1'] = [int(rec[858:860])]
    record['pxhspnon'] = [int(rec[860:862])]
    record['pxcohab'] = [int(rec[862:864])]
    record['pxlnmom'] = [int(rec[864:866])]
    record['pxlndad'] = [int(rec[866:868])]
    record['pxmomtyp'] = [int(rec[868:870])]
    record['pxdadtyp'] = [int(rec[870:872])]
    record['pxafever'] = [int(rec[872:874])]
    record['pxafwhn1'] = [int(rec[874:876])]
    record['pxdisear'] = [int(rec[876:878])]
    record['pxdiseye'] = [int(rec[878:880])]
    record['pxdisrem'] = [int(rec[880:882])]
    record['pxdisphy'] = [int(rec[882:884])]
    record['pxdisdrs'] = [int(rec[884:886])]
    record['pxdisout'] = [int(rec[886:888])]
    record['pxnatvty'] = [int(rec[888:890])]
    record['pxmntvty'] = [int(rec[890:892])]
    record['pxfntvty'] = [int(rec[892:894])]
    record['pxinusyr'] = [int(rec[894:896])]
    record['prwernal'] = [int(rec[896])]
    record['prhernal'] = [int(rec[897])]
    record['axhrs'] = [int(rec[898])]
    record['axwhyabs'] = [int(rec[899])]
    record['axpayabs'] = [int(rec[900])]
    record['axclswkr'] = [int(rec[901])]
    record['axnlflj'] = [int(rec[902])]
    record['axuslhrs'] = [int(rec[903])]
    record['axhrlywk'] = [int(rec[904])]
    record['axunmem'] = [int(rec[905])]
    record['axuncov'] = [int(rec[906])]
    record['axenrlw'] = [int(rec[907])]
    record['axhscol'] = [int(rec[908])]
    record['axftpt'] = [int(rec[909])]
    record['axlfsr'] = [int(rec[910])]
    record['i_workyn'] = [int(rec[911])]
    record['i_wtemp'] = [int(rec[912])]
    record['i_nwlook'] = [int(rec[913])]
    record['i_nwlkwk'] = [int(rec[914])]
    record['i_rsnnot'] = [int(rec[915])]
    record['i_wkswk'] = [int(rec[916])]
    record['i_wkchk'] = [int(rec[917])]
    record['i_losewk'] = [int(rec[918])]
    record['i_lkweek'] = [int(rec[919])]
    record['i_lkstr'] = [int(rec[920])]
    record['i_pyrsn'] = [int(rec[921])]
    record['i_phmemp'] = [int(rec[922])]
    record['i_hrswk'] = [int(rec[923])]
    record['i_hrchk'] = [int(rec[924])]
    record['i_ptyn'] = [int(rec[925])]
    record['i_ptwks'] = [int(rec[926])]
    record['i_ptrsn'] = [int(rec[927])]
    record['i_ljcw'] = [int(rec[928])]
    record['i_indus'] = [int(rec[929])]
    record['i_occup'] = [int(rec[930])]
    record['i_noemp'] = [int(rec[931])]
    record['i_nxtres'] = [int(rec[932])]
    record['i_mig1'] = [int(rec[933])]
    record['i_mig2'] = [int(rec[934:936])]
    record['i_mig3'] = [int(rec[936])]
    record['i_disyn'] = [int(rec[937])]
    record['i_ernyn'] = [int(rec[938])]
    record['i_ernsrc'] = [int(rec[939])]
    record['i_ernval'] = [int(rec[940])]
    record['i_retsc2'] = [int(rec[941])]
    record['i_wsyn'] = [int(rec[942])]
    record['i_wsval'] = [int(rec[943])]
    record['i_seyn'] = [int(rec[944])]
    record['i_seval'] = [int(rec[945])]
    record['i_frmyn'] = [int(rec[946])]
    record['i_frmval'] = [int(rec[947])]
    record['i_ucyn'] = [int(rec[948])]
    record['i_ucval'] = [int(rec[949])]
    record['i_wcyn'] = [int(rec[950])]
    record['i_wctyp'] = [int(rec[951])]
    record['i_wcval'] = [int(rec[952])]
    record['i_ssyn'] = [int(rec[953])]
    record['i_ssval'] = [int(rec[954])]
    record['resnssa'] = [int(rec[955])]
    record['i_ssiyn'] = [int(rec[956])]
    record['sskidyna'] = [int(rec[957])]
    record['i_ssival'] = [int(rec[958])]
    record['resnssia'] = [int(rec[959])]
    record['i_pawyn'] = [int(rec[960])]
    record['ssikdyna'] = [int(rec[961])]
    record['i_pawtyp'] = [int(rec[962])]
    record['i_pawmo'] = [int(rec[963])]
    record['i_pawval'] = [int(rec[964])]
    record['i_vetyn'] = [int(rec[965])]
    record['i_vettyp'] = [int(rec[966])]
    record['i_vetqva'] = [int(rec[967])]
    record['i_vetval'] = [int(rec[968])]
    record['i_suryn'] = [int(rec[969])]
    record['i_sursc1'] = [int(rec[970])]
    record['i_sursc2'] = [int(rec[971])]
    record['i_survl1'] = [int(rec[972])]
    record['i_survl2'] = [int(rec[973])]
    record['i_dishp'] = [int(rec[974])]
    record['i_discs'] = [int(rec[975])]
    record['i_dissc1'] = [int(rec[976])]
    record['i_dissc2'] = [int(rec[977])]
    record['i_disvl1'] = [int(rec[978])]
    record['i_disvl2'] = [int(rec[979])]
    record['i_retyn'] = [int(rec[980])]
    record['i_retsc1'] = [int(rec[981])]
    record['i_retvl1'] = [int(rec[982])]
    record['i_retvl2'] = [int(rec[983])]
    record['i_intyn'] = [int(rec[984])]
    record['i_intval'] = [int(rec[985])]
    record['i_divyn'] = [int(rec[986])]
    record['i_divval'] = [int(rec[987])]
    record['i_rntyn'] = [int(rec[988])]
    record['i_rntval'] = [int(rec[989])]
    record['i_edyn'] = [int(rec[990])]
    record['i_edtyp1'] = [int(rec[991])]
    record['i_edtyp2'] = [int(rec[992])]
    record['i_oedval'] = [int(rec[993])]
    record['i_cspyn'] = [int(rec[994])]
    record['i_cspval'] = [int(rec[995])]
    record['i_finyn'] = [int(rec[998])]
    record['i_finval'] = [int(rec[999])]
    record['i_oival'] = [int(rec[1000])]
    record['wicyna'] = [int(rec[1001])]
    record['i_hi'] = [int(rec[1002])]
    record['i_dephi'] = [int(rec[1003])]
    record['i_paid'] = [int(rec[1004])]
    record['i_hiout'] = [int(rec[1005])]
    record['i_priv'] = [int(rec[1006])]
    record['i_depriv'] = [int(rec[1007])]
    record['i_pout'] = [int(rec[1008])]
    record['i_out'] = [int(rec[1009])]
    record['i_care'] = [int(rec[1010])]
    record['i_caid'] = [int(rec[1011])]
    record['i_mon'] = [int(rec[1012])]
    record['i_oth'] = [int(rec[1013])]
    record['i_otyp'] = [int(rec[1014])]
    record['i_ostper'] = [int(rec[1015])]
    record['i_ostyp'] = [int(rec[1016])]
    record['i_hea'] = [int(rec[1017])]
    record['iahiper'] = [int(rec[1018])]
    record['iahityp'] = [int(rec[1019])]
    record['i_pchip'] = [int(rec[1020])]
    record['i_penpla'] = [int(rec[1021])]
    record['i_peninc'] = [int(rec[1022])]
    record['i_phipval'] = [int(rec[1023])]
    record['i_potcval'] = [int(rec[1024])]
    record['i_pmedval'] = [int(rec[1025])]
    record['i_chspval'] = [int(rec[1026])]
    record['i_chspyn'] = [int(rec[1027])]
    record['i_chelsewyn'] = [int(rec[1028])]
    record['a_werntf'] = [int(rec[1049])]
    record['a_herntf'] = [int(rec[1050])]
    record['tcernval'] = [int(rec[1051])]
    record['tcwsval'] = [int(rec[1052])]
    record['tcseval'] = [int(rec[1053])]
    record['tcffmval'] = [int(rec[1054])]
    record['tsurval1'] = [int(rec[1055])]
    record['tsurval2'] = [int(rec[1056])]
    record['tdisval1'] = [int(rec[1057])]
    record['tdisval2'] = [int(rec[1058])]
    record['tretval1'] = [int(rec[1059])]
    record['tretval2'] = [int(rec[1060])]
    record['tint_val'] = [int(rec[1061])]
    record['tdiv_val'] = [int(rec[1062])]
    record['trnt_val'] = [int(rec[1063])]
    record['ted_val'] = [int(rec[1064])]
    record['tcsp_val'] = [int(rec[1065])]
    record['tfin_val'] = [int(rec[1067])]
    record['toi_val'] = [int(rec[1068])]
    record['tphip_val'] = [int(rec[1069])]
    record['tpotc_val'] = [int(rec[1070])]
    record['tpmed_val'] = [int(rec[1071])]
    record['tchsp_val'] = [int(rec[1072])]

    return pd.DataFrame(record)


def create_cps(raw_cps):
    """
    Function to start process of creating the CPS file

    Parameters
    ----------
    raw_cps: String containing path to CPS file in DAT format as downloaded
             from the NBER website

    Returns
    -------
    CPS file as a pandas DF
    """
    # Read in CPS file
    cps = [line.strip().split() for line in
           open(raw_cps).readlines()]

    # Empty list to hold the completed records
    cps_list = []
    print('Creating Records')
    for record in tqdm(cps):
        # Find the type of record
        rectype = record[0][0]
        if rectype == '1':
            # If it's a household, hold that record to concat to family records
            house_rec = h_recs(record[0])
        elif rectype == '2':
            # If it's a family record, concat to household record and store
            house_fam = pd.concat([house_rec, f_recs(record[0])], axis=1,
                                  sort=False)
        else:
            # If it's a person record, concat to household and family record
            final_rec = pd.concat([house_fam, p_recs(record[0])], axis=1,
                                  sort=False)
            # Append final record to the list of records
            cps_list.append(final_rec)

    # Create the data set by combining all of the records
    cps_mar = pd.concat(cps_list, sort=False)
    # Export the data
    print('Exporting Data')
    cps_mar.to_csv('cpsmar2016.csv', index=False)
    return cps_mar
